- platform: mqtt
  # Lichterkette Eingangsbereich
  name: "gf_free_outlet_2"
  command_topic: "rc433/groundfloor/gf_free_outlet_2/switch"
  state_topic: "rc433/groundfloor/gf_free_outlet_2/state"
  retain: false

# Groundfloor
- platform: mqtt
  name: "gf_kitchen_workplace"
  command_topic: "rc433/groundfloor/gf_kitchen_workplace/switch"
  state_topic: "rc433/groundfloor/gf_kitchen_workplace/state"
  retain: false

- platform: mqtt
  name: "gf_kitchen_window"
  command_topic: "rc433/groundfloor/gf_kitchen_window/switch"
  state_topic: "rc433/groundfloor/gf_kitchen_window/state"
  retain: false

- platform: mqtt
  name: "gf_livingroom_outlet"
  command_topic: "rc433/groundfloor/gf_livingroom_outlet/switch"
  state_topic: "rc433/groundfloor/gf_livingroom_outlet/state"
  retain: false

# Firstfloor
- platform: mqtt
  name: "ff_floor_tree"
  command_topic: "rc433/firstfloor/ff_floor_tree/switch"
  state_topic: "rc433/firstfloor/ff_floor_tree/state"
  retain: false

- platform: mqtt
  name: "ff_mika_bed"
  command_topic: "rc433/firstfloor/ff_mika_bed/switch"
  state_topic: "rc433/firstfloor/ff_mika_bed/state"
  retain: false
# Freie Radikale
- platform: mqtt
  name: "ff_mika_outlet"
  command_topic: "rc433/firstfloor/ff_mika_outlet/switch"
  state_topic: "rc433/firstfloor/ff_mika_outlet/state"
  retain: false

- platform: mqtt
  name: "ff_jona_bed"
  command_topic: "rc433/firstfloor/ff_jona_bed/switch"
  state_topic: "rc433/firstfloor/ff_jona_bed/state"
  retain: false

- platform: mqtt
  name: "ff_jona_outlet"
  command_topic: "rc433/firstfloor/ff_jona_outlet/switch"
  state_topic: "rc433/firstfloor/ff_jona_outlet/state"
  retain: false


# Secondfloor
- platform: mqtt
  name: "sf_floor_work_outlet"
  command_topic: "rc433/secondfloor/sf_floor_work_outlet/switch"
  state_topic: "rc433/secondfloor/sf_floor_work_outlet/state"
  retain: false

- platform: mqtt
  name: "sf_floor_work_desk"
  command_topic: "rc433/secondfloor/sf_floor_work_desk/switch"
  state_topic: "rc433/secondfloor/sf_floor_work_desk/state"
  retain: false

- platform: mqtt
  name: "sf_floor_work_shelf"
  command_topic: "rc433/secondfloor/sf_floor_work_shelf/switch"
  state_topic: "rc433/secondfloor/sf_floor_work_shelf/state"
  retain: false

- platform: mqtt
  name: "sf_bedroom_outlet"
  command_topic: "rc433/secondfloor/sf_bedroom_outlet/switch"
  state_topic: "rc433/secondfloor/sf_bedroom_outlet/state"
  retain: false

