listen_port: 80
upnp_bind_multicast: true
expose_by_default: false
exposed_domains:
  - switch
  - light
  - group
  - input_boolean
entities:
  # group.ground_floor_lights:
  #   name: "Erdgeschoss"
  #   hidden: false
  # light.jeq0207534:
  #   name: "Essplatz"
  #   hidden: false
  # group.livingroom_couch:
  #   name: "Sofa"
  #   hidden: false
  # light.meq0397149:
  #   name: "Eingangsbereich"
  #   hidden: false
  # switch.feq0062058:
  #   name: "Gartenlicht"
  #   hidden: false
  # switch.gf_kitchen_workplace:
  #   name: "Arbeitsplatte"
  #   hidden: false

  group.first_floor_lights:
    name: "Obergeschoss"
    hidden: false
  group.ff_floor_lights:
    name: "Flur"
    hidden: false
  switch.ff_jona_bed:
    name: "Jona Bett"
    hidden: false
  switch.ff_jona_outlet:
    name: "Jona Lichterkette"
    hidden: false
  light.jona_bunt:
    name: "Jona Schreibtisch"
    hidden: false
  group.ff_bathroom_lights:
    name: "Badezimmer"
    hidden: false
  light.shelly_dim_ff_bathroom_ceiling:
    name: "Badezimmer Decke"
    hidden: false
  light.shelly_dim_ff_bathroom_wall:
    name: "Badezimmer Wand"
    hidden: false

  light.shelly_rgbw_ff_mika_led_strip:
    name: "Mika LED Wand"
    hidden: false

  group.second_floor_lights:
    name: "Dachgeschoss"
    hidden: false
  group.sf_bedroom_lights:
    name: "Schlafzimmer"
    hidden: false
  switch.sf_bedroom_outlet:
    name: "Kommode"
    hidden: false
  switch.sf_bedroom_bed:
    name: "Bett"
    hidden: false
  group.sf_work_lights:
    name: "Arbeitszimmer"
    hidden: false
  switch.sf_floor_work_outlet:
    name: "Regal"
    hidden: false
  switch.sf_floor_work_desk:
    name: "Schreibtisch"
    hidden: false