
# Homematic
switch.feq0062058:
  icon: mdi:lightbulb
  friendly_name: Gartenlicht

light.heq0359760:
  friendly_name: Lampe 1
  
light.jeq0207534:
  friendly_name: Küche - Essplatz

light.jeq0207545:
  friendly_name: Eingang

light.jeq0207587:
  friendly_name: Außenlicht

light.meq0169146:
  friendly_name: Wohnzimmer

light.meq0397149:
  friendly_name: Flurwand

# Switches

switch.gf_kitchen_workplace:
  friendly_name: Küche Arbeitsplatte
  assumed_state: false

switch.gf_kitchen_window: 
  friendly_name: Küche Fenster
  assumed_state: false

switch.ff_floor_tree:
  friendly_name: Flur (Baum)
  assumed_state: false

switch.ff_mika_bed:
  friendly_name: Mika Lichterkette
  assumed_state: false

switch.ff_jona_bed:
  friendly_name: Jona Lichterkette
  assumed_state: false

switch.sf_floor_work_outlet:
  friendly_name: Arbeitszimmer Sofa
  assumed_state: false

switch.sf_bedroom_outlet:
  friendly_name: Schlafzimmer Kommode
  assumed_state: false

switch.sf_bedroom_bed:
  friendly_name: Schlafzimmer Bett
  assumed_state: false

# Aeotec Sensor 6

sensor.aeotec_zw100_multisensor_6_temperature:
  friendly_name: Temperatur 1. OG

sensor.aeotec_zw100_multisensor_6_luminance:
  friendly_name: Helligkeit 1. OG

sensor.aeotec_zw100_multisensor_6_burglar:
  friendly_name: Bewegungsmelder 1. OG

# HASS Versions

sensor.ha_online_version:
  friendly_name: Online Version

sensor.current_version:
  friendly_name: Aktuelle Version


# Tradfri

light.links:
  friendly_name: Sofa links

light.rechts:
  friendly_name: Sofa rechts

light.sofa:
  friendly_name: Sofa

# Mediaplayer

media_player.yamaha_receiver:
  friendly_name: RX-1030 Wohnzimmer

media_player.yamaha_receiver_zone_2:
  friendly_name: RX-1030 Küche

media_player.viera_gt30_series:
  friendly_name: Fernseher


# Weather
sensor.weather_cloudiness:
  friendly_name: Cloudiness
  icon: mdi:cloud-outline

sensor.weather_humidity:
  friendly_name: Humidity (Outdoor)
  icon: mdi:water-percent

sensor.weather_symbol:
  friendly_name: Weather

sensor.weather_temperature:
  friendly_name: Temperature

# Calendar
sensor.femke_schedule:
  icon: mdi:calendar

sensor.mirko_schedule:
  icon: mdi:calendar

sensor.family_schedule:
  icon: mdi:calendar

# System

sensor.net_rate_up_max:
  friendly_name: Max Up

sensor.net_rate_down_max:
  friendly_name: Max Down

# Trashcans
sensor.trash:
  friendly_name: Müll
  icon: mdi:delete

# Scenes
scene.groundfloor_lights:
  icon: mdi:google-fit

scene.dinner:
  icon: mdi:food-fork-drink

scene.blockbuster:
  icon: mdi:youtube-tv

# Scripts
script.yamaha_net_radio:
  friendly_name: Start Playing
  icon: mdi:play

script.yamaha_net_radio_zone2:
  friendly_name: Start Playing (Küche)
  icon: mdi:play