# Persons

person.mirko:
  entity_picture: /local/images/mirko.jpg

person.femke:
  entity_picture: /local/images/femke.jpg

person.mika:
  entity_picture: /local/images/mika.jpg

person.jona:
  entity_picture: /local/images/jona.jpg

#
# Homematic
#
switch.feq0062058:
  icon: mdi:lightbulb
  friendly_name: Gartenlicht

light.heq0359760:
  friendly_name: Spüle

light.homegear_eg_sink:
  friendly_name: Spüle (MQTT)

# Küche
light.jeq0207534:
  friendly_name: Essplatz

light.homegear_eg_table:
  friendly_name: Essplatz (MQTT)

# Eingangsbereich
light.jeq0207545:
  friendly_name: Flur

light.homegear_eg_entrance:
  friendly_name: Flur (MQTT)

# Eingangsbereich
light.jeq0207587:
  friendly_name: Außenlicht

light.homegear_eg_doorlight:
  friendly_name: Außenlicht (MQTT)

# Fahrräder
light.shelly_dim_eg_bicycles:
  friendly_name: Fahrräder

# Wohnzimmer
light.meq0169146:
  friendly_name: Decke

light.homegear_eg_living_room:
  friendly_name: Decke (MQTT)


# OG Flur
light.meq0397149:
  friendly_name: Flurwand

light.homegear_ff_hallway:
  friendly_name: Flurwand (MQTT)

#
# Switches
#

switch.gf_free_outlet_2:
  # Eingangsbereich
  friendly_name: Lichterkette
  assumed_state: false

switch.gf_kitchen_workplace:
  friendly_name: Arbeitsplatte
  assumed_state: false
  automation:
    initial_state: 'off'

switch.gf_kitchen_window:
  friendly_name: Fenster
  assumed_state: false

switch.gf_livingroom_outlet:
  friendly_name: Leiter
  assumed_state: false


switch.ff_floor_tree:
  friendly_name: Baum
  assumed_state: false

switch.ff_mika_outlet:
  friendly_name: Computer
  assumed_state: false

light.shelly_rgbw_ff_mika_led_strip:
  friendly_name: LED Wand
  assumed_state: false

sensor.shelly_rgbw_ff_mika_led_power:
  friendly_name: LED Wand
  assumed_state: false

switch.ff_jona_bed:
  friendly_name: Bett
  assumed_state: false

switch.ff_jona_outlet:
  friendly_name: Steckdose
  assumed_state: false

light.shelly_dim_ff_bathroom_ceiling:
  friendly_name: Decke
  assumed_state: false

sensor.shelly_dim_ff_bathroom_ceiling_power:
  friendly_name: Decke
  assumed_state: false


switch.sf_floor_work_outlet:
  friendly_name: Regal (Sofa)
  assumed_state: false

switch.sf_floor_work_desk:
  friendly_name: Schreibtisch
  assumed_state: false
  icon: mdi:television

switch.sf_floor_work_shelf:
  friendly_name: Regal (Drucker)
  assumed_state: false

switch.sf_bedroom_outlet:
  friendly_name: Kommode
  assumed_state: false

switch.sf_bedroom_bed:
  friendly_name: Lichterkette Bett
  assumed_state: false


# Aeotec Sensor 6

sensor.aeotec_zw100_multisensor_6_temperature:
  friendly_name: Temperatur 1. OG

sensor.aeotec_zw100_multisensor_6_luminance:
  friendly_name: Helligkeit 1. OG

sensor.aeotec_zw100_multisensor_6_burglar:
  friendly_name: Bewegungsmelder 1. OG

# HASS Versions

sensor.ha_online_version:
  friendly_name: Online Version

sensor.current_version:
  friendly_name: Aktuelle Version


# Tradfri

light.links:
  friendly_name: Sofa links

light.rechts:
  friendly_name: Sofa rechts

light.garderobe1:
  friendly_name: Garderobe 1

light.mika_klavier:
  friendly_name: Klavier

group.living_room_couch:
  friendly_name: Sofa
  icon: mdi:lightbulb

# Mediaplayer

media_player.yamaha_receiver:
  friendly_name: RX-1030 Wohnzimmer

media_player.yamaha_receiver_zone_2:
  friendly_name: RX-1030 Küche

media_player.panasonic_viera_tv:
  friendly_name: Fernseher

media_player.echo_badezimmer:
  friendly_name: Alexa Badezimmer

media_player.echo_dg_schlafzimmer:
  friendly_name: Alexa Schlafzimmer

media_player.echo_dg_arbeitszimmer:
  friendly_name: Alexa Arbeitszimmer

# Weather

sensor.dark_sky_cloud_coverage:
  friendly_name: Cloudiness
  icon: mdi:cloud-outline

sensor.dark_sky_humidity:
  friendly_name: Humidity (Outdoor)
  icon: mdi:water-percent

sensor.dark_sky_temperature:
  friendly_name: Temperature


# Calendar
sensor.femke_schedule:
  icon: mdi:calendar

sensor.mirko_schedule:
  icon: mdi:calendar

sensor.family_schedule:
  icon: mdi:calendar

# System

sensor.net_rate_up_max:
  friendly_name: Max Up

sensor.net_rate_down_max:
  friendly_name: Max Down

# Trashcans

binary_sensor.srhh_morgen_blau:
  friendly_name: Blau
  icon: mdi:delete
  automation:
    initial_state: 'off'

binary_sensor.srhh_morgen_gruen:
  friendly_name: Grün
  icon: mdi:delete
  automation:
    initial_state: 'off'

binary_sensor.srhh_morgen_gelb:
  friendly_name: Gelb
  icon: mdi:delete
  automation:
    initial_state: 'off'

binary_sensor.srhh_morgen_schwarz:
  friendly_name: Schwarz
  icon: mdi:delete
  automation:
    initial_state: 'off'

# Scenes

scene.groundfloor_lights:
  icon: mdi:google-fit

scene.dinner:
  icon: mdi:food-fork-drink

scene.blockbuster:
  icon: mdi:youtube-tv
  
scene.lunch_notification:
  icon: mdi:hand-heart

# Scripts

script.yamaha_net_radio:
  friendly_name: Start Playing
  icon: mdi:play

script.yamaha_net_radio_zone2:
  friendly_name: Start Playing (Küche)
  icon: mdi:play

script.mika_night_mode:
  friendly_name: Night Mode
  icon: mdi:emoticon-dead

script.mika_warm_white:
  friendly_name: Warm White
  icon: mdi:white-balance-sunny