- platform: fritz
  host: fritz.box
  consider_home: 90
  interval_seconds: 30 
  track_new_devices: False

# - platform: nmap_tracker
#   hosts: 192.168.178.0/24
#   consider_home: 90
#   track_new_devices: False  
#   interval_seconds: 300
#   # nmap specific
#   home_interval: 90

- platform: owntracks
  waypoints: False
  track_new_devices: False

# - platform: bluetooth_tracker