alexas:
  name: Alexas
  entities:
    - media_player.alexas_echo_dot
    - media_player.echo_dg_arbeitszimmer
    - media_player.echo_dg_schlafzimmer
    - media_player.mikas_echo
    - media_player.jonas_echo

sf_alexas:
  name: Alexas
  entities:
    - media_player.echo_dg_arbeitszimmer
    - media_player.echo_dg_schlafzimmer