mirko:
  name: Mirko
  entities:
    - person.mirko
    # - device_tracker.mirko_mobile_app
    # - device_tracker.galaxy_s10
    # - device_tracker.bt_mirko_gf
    # - device_tracker.bt_mirko_ff
    # - device_tracker.bt_mirko_sf
    # - sensor.bt_presence_mirko

femke:
  name: Femke
  entities:
    - person.femke
    #  - device_tracker.iphone_femke
    # - device_tracker.femke_mobile_app
    # - device_tracker.bt_femke_gf
    # - device_tracker.bt_femke_ff
    # - device_tracker.bt_femke_sf
    # - sensor.bt_presence_femke

mika:
  name: Mika
  entities:
    - person.mika
    # - device_tracker.iphone_mika
    # - device_tracker.mika_mobile_app
    # - device_tracker.bt_mika_gf
    # - device_tracker.bt_mika_ff
    # - device_tracker.bt_mika_sf
    # - sensor.bt_presence_mika

jona:
  name: Jona
  entities:
    - person.jona
    # - device_tracker.huawei_jona
    # - device_tracker.jona_mobile_app
    # - device_tracker.bt_jona_gf
    # - device_tracker.bt_jona_ff
    # - device_tracker.bt_jona_sf


kids:
  name: Kinder
  entities:
    - group.mika
    - group.jona

parents:
  name: Eltern
  entities:
    - group.mirko
    - group.femke

family:
  name: Familie
  entities:
    - group.parents
    - group.kids

trusted_friends:
  name: Freunde und Bekannte
  entities:
    - device_tracker.matschy_iphone
    - device_tracker.franksiphone8s
    - device_tracker.iphone_cclausen
    - device_tracker.meins
    - device_tracker.iphoneocknorris
