mirko:
  name: Mirko
  entities:
    - device_tracker.iphone_mirko
    - device_tracker.mirko_owntracks

femke:
  name: Femke
  entities:
    - device_tracker.iphone_femke
   # - device_tracker.femke_owntracks

mika:
  name: Mika
  entities:
    - device_tracker.huawei_mika

kids:
  name: Kinder
  entities:
    - group.mika

parents:
  name: Eltern
  entities:
    - group.mirko
    - group.femke

family:
  name: Familie
  entities:
    - group.parents
    - group.kids

trusted_friends:
  name: Freunde und Bekannte
  entities:
    - device_tracker.iphone_sepp
    - device_tracker.iphone_frank    