
mika_devices:
  name: Mika Ger√§te
  entities:
    - group.mika_lights
    - group.mika_computer

mika_lights:
  name: Mika Lichter
  entities:
    - light.shelly_rgbw_ff_mika_led_strip

mika_multimedia:
  name: Mika Multimedia
  entities:
    - media_player.mikas_echo

mika_scenes:
  name: Mika Szenen
  entities:
    - script.mika_warm_white
    - script.mika_night_mode
    
mika_alarm_clock:
  name: Wecker
  entities:
    - input_boolean.alarm_clock_mika
    - input_datetime.alarm_clock_time_mika

mika_computer:
  name: PC Stuff
  entities:
    - switch.ff_mika_outlet