second_floor:
  name: Dachgeschoss
  entities:
    - group.sf_work
    - group.sf_bedroom

second_floor_multimedia:
  name: Dachgeschoss Media
  entities:
    - group.sf_work_multimedia
    - group.sf_bedroom_multimedia    

second_floor_lights:
  name: Dachgeschoss Licht
  entities:
    - group.sf_work_lights
    - group.sf_bedroom_lights    

sf_work:
  name: Arbeitszimmer
  entities:
    - group.sf_work_lights
    - group.sf_work_multimedia

sf_work_lights:
  name: Arbeitszimmer Licht
  entities:
    - switch.sf_floor_work_desk
    - switch.sf_floor_work_outlet
    - switch.sf_floor_work_shelf

sf_work_mood_lights:
  name: Arbeitszimmer Licht
  entities:
    - switch.sf_floor_work_outlet
    - switch.sf_floor_work_shelf

sf_work_multimedia:
  name: Arbeitszimmer Media
  entities:
    - media_player.echo_dg_arbeitszimmer

sf_bedroom:
  name: Schlafzimmer
  entities:
    - group.sf_bedroom_lights
    - group.sf_bedroom_multimedia

sf_bedroom_lights:
  name: Schlafzimmer Licht
  entities:
    - switch.sf_bedroom_outlet
    - switch.sf_bedroom_bed

sf_bedroom_multimedia:
  name: Schlafzimmer Media
  entities:
    - media_player.echo_dg_schlafzimmer