second_floor:
  name: Dachgeschoss
  entities:
    - group.sf_work_lights
    - group.sf_work_media
    - group.sf_bedroom_lights    

second_floor_lights:
  name: Dachgeschoss
  entities:
    - group.sf_work_lights
    - group.sf_bedroom_lights    

sf_work_media:
  name: Arbeitszimmer Media
  entities:
    - media_player.volumio

sf_work_lights:
  name: Arbeitszimmer
  entities:
    - switch.sf_floor_work_outlet

sf_bedroom_lights:
  name: Schlafzimmer
  entities:
    - switch.sf_bedroom_outlet
    - switch.sf_bedroom_bed