
default_view:
  name: Home
  icon: mdi:home
  entities:
    - group.home_lights
    # - group.family_status
    - group.weather_dashboard
    - group.calendars


view_ground_floor:
  name: EG
  entities:
    - group.kitchen_lights
    - group.livingroom_lights
    - group.entree_lights
    - group.garden_lights
    - group.kitchen_media
    - group.livingroom_media
    - group.yamaha_radio


view_first_floor:
  name: OG
  entities:
    - sensor.aeotec_zw100_multisensor_6_temperature
    - sensor.aeotec_zw100_multisensor_6_luminance
    - sensor.aeotec_zw100_multisensor_6_burglar
    - group.ff_floor_lights
    - group.ff_mika
    - group.ff_jona
    - media_player.echo_badezimmer


view_second_floor:
  name: DG
  entities:
    - group.sf_work_lights
    - group.sf_bedroom_lights


view_rest:
  name: Dies&Das
  icon: mdi:creation
  entities:
    - group.scenes
    #- group.family_status
    - group.boolean_states


view_system:
  name: System
  icon: mdi:cogs
  entities:
    - group.speedtest
    - group.hass_versions
    - group.raspi
    - group.batteries

# view_weather:
#   name: Wetter
#   icon: mdi:cloud
#   entities:
#     - group.weather_darksky
#     - group.airdata
#     - sun.sun    