airdata:
  entities:
    - sensor.luftdaten_14343_humidity    
    - sensor.luftdaten_14343_temperature

weather_dashboard:
  name: Wetter
  view: false
  entities:
  - sensor.dark_sky_temperature
  - sensor.dark_sky_humidity
  - sensor.dark_sky_cloud_coverage

weather_darksky:
  name: Wetter
  view: false
  entities:
  - sensor.dark_sky_summary
  - sensor.dark_sky_daily_summary  
  - sensor.dark_sky_temperature
  - sensor.dark_sky_apparent_temperature
  - sensor.dark_sky_daytime_high_temperature  
  - sensor.dark_sky_wind_speed
  - sensor.dark_sky_visibility
  - sensor.dark_sky_humidity
  - sensor.dark_sky_cloud_coverage