- platform: yamaha
  host: RX-A1030-A2E197
  # zone_ignore: 
  #   - "Zone_2"
  source_ignore:
    - "AUDIO2"
    - "AUDIO3"
    - "AUDIO4"
    - "AV2" 
    - "AV3" 
    - "AV4" 
    - "AV5" 
    - "AV6" 
    - "AV7" 
    - "MULTI CH" 
    - "Napster" 
    - "Phono"
    - "iPod (USB)"
    - "V-AUX"
    - "USB"
    - "Server" 
    - "Tuner"